# TODO
name: Run Comfy-PR Hourly.

on:
  schedule:
    - cron: "55 * * * *" # Runs every the 55th minute
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - ".github/workflows/*"
      - "src/*.ts"
jobs:
  run_comfy_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # setup comfy-cli
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: python -m pip install --upgrade pip
      - run: python -m venv .venv
      - run: source .venv/bin/activate
      - run: pip install comfy-cli
      # Setup SSH Key for git push
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # Setup Bun
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: oven-sh/setup-bun@v1
      # Run Comfy-PR Worker
      - run: bun i
      - run: bun src/index.ts
        env:
          COMFY_PR_REPO: ${{ secrets.COMFY_PR_REPO }}
          FORK_OWNER: "ComfyNodePRs"
          FORK_PREFIX: "PR-"
          GH_TOKEN_COMFY_PR: ${{ secrets.GH_TOKEN_COMFY_PR }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SLACK_BOT_CHANNEL: ${{ secrets.SLACK_BOT_CHANNEL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
